import ToasterProvider from '@/providers/ToasterProvider';
import Register from './components/models/Register';
import './globals.css';
import getCurrentUser from './actions/getCurrentUser';
import Authentication from './auth/page';

export const metadata = {
   title: 'Facebook App',
   description: 'Generated by create next app',
};

export default async function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   const currentUser = await getCurrentUser();
   return (
      <html lang="en">
         <body>
            <ToasterProvider />
            <Register />
            {!currentUser && <Authentication />}
            {currentUser && children}
         </body>
      </html>
   );
}
